config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|vi/ do
    root "static_pages#home"

    get "/about", to: "static_pages#about"
    get "/contact", to: "static_pages#contact"
    get "/term", to: "static_pages#term"
    get "/security", to: "static_pages#security"
    get "/order_details", to: "order_details#index"

    as :user do
      get "signup", to: "users/registrations#new"
      get "signin", to: "devise/sessions#new"
      post "signin", to: "devise/sessions#create"
      delete "signout", to: "devise/sessions#destroy"
      get "profile", to: "devise/registrations#edit"
      put "profile", to: "devise/registrations#update"
    end

    devise_for :users, controllers: {registrations: "users/registrations"}

    resources :users, only: [:show, :edit, :update]
    resources :restaurants do
      member do
        get :orders
      end
    end
    resources :orders, except: %i(edit destroy)
    resources :dishes
    resources :combos
  end
end

app/views/shared/_button.html.erb
<% if order.pending? %>
  <% if current_user.boss? %>
    <%= form_tag order_path(order, res_id: @restaurant.id), method: :patch, remote: true do %>
     <%= hidden_field_tag "status", Order.statuses[:accepted] %>
      <button type="submit" class="btn btn-none-bg btn-login">
        <%= t "accept" %>
      </button>
    <% end %>
    <%= form_tag order_path(order, res_id: @restaurant.id), method: :patch, remote: true do %>
      <%= hidden_field_tag "status", Order.statuses[:cancel] %>
      <button type="submit" class="btn btn-none-bg btn-login">
        <%= t "cancel" %>
      </button>
    <% end %>
  <% else %>
    <%= form_tag order_path(order), method: :patch, remote: true do %>
      <%= hidden_field_tag "status", Order.statuses[:cancel] %>
      <button type="submit" class="btn btn-none-bg btn-login">
        <%= t "cancel" %>
      </button>
    <% end %>
  <% end %>
<% end %>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      <%= t "size_error", sum: object.errors.size %>.
    </div>
    <ul>
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_nav_item.html.erb
<div class="item-navigation <%= active_navigation restaurant %>">
  <div class="row">
    <div class="col-auto">
      <i class="fas fa-utensils"></i>
    </div>
    <div class="col" title="<%= restaurant.name %>">
      <%= restaurant.name %>
    </div>
    <div class="col-auto">
      <i class="nav-icon-arrow-thin down"></i>
    </div>
  </div>
  <div class="sub-navigation <%= show_sub_navigation restaurant %>">
    <%= link_to edit_restaurant_path(restaurant), title: t("update_info"),
      target: "_self" do %>
      <div class="sub-item-navigation
        <%= active_update_restaurant restaurant %>">
        <div class="row">
          <div class="col-auto">
            <i class="fas fa-info"></i>
          </div>
          <div class="col"><%= t "update_info" %></div>
          <div class="col-auto">
            <i class="sub-nav-icon-arrow-thin right"></i>
          </div>
        </div>
      </div>
    <% end %>
    <%= link_to dishes_path(res_id: restaurant.id), title: t("dishes_list"),
      target: "_self" do %>
      <div class="sub-item-navigation <%= active_dishes_list restaurant %>">
        <div class="row">
          <div class="col-auto">
            <i class="fas fa-pizza-slice"></i>
          </div>
          <div class="col"><%= t"dishes_list" %></div>
          <div class="col-auto">
            <i class="sub-nav-icon-arrow-thin right"></i>
          </div>
        </div>
      </div>
    <% end %>
    <%= link_to combos_path(res_id: restaurant.id), title: t("combos_list"), target: "_self" do %>
      <div class="sub-item-navigation <%= active_combos_list restaurant %>">
        <div class="row">
          <div class="col-auto">
            <i class="fas fa-hamburger"></i>
          </div>
          <div class="col"><%= t "combos_list" %></div>
          <div class="col-auto">
            <i class="sub-nav-icon-arrow-thin right"></i>
          </div>
        </div>
      </div>
    <% end %>
    <%= link_to orders_restaurant_path(restaurant), title: t("all_order"),
      target: "_self" do %>
      <div class="sub-item-navigation <%= active_orders_list restaurant %>">
        <div class="row">
          <div class="col-auto">
            <i class="fas fa-file-alt"></i>
          </div>
          <div class="col"><%= t "all_order" %></div>
          <div class="col-auto">
            <i class="sub-nav-icon-arrow-thin right"></i>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/shared/_navigation.html.erb
<div class="now-navigation-profile">
  <div class="header-profile">
    <div class="row align-items-center">
      <div class="col-auto">
        <%= image_tag current_user.image, class: "avatar-circle",
          alt: current_user.name %>
      </div>
      <div class="col txt-bold font15"><%= current_user.name %></div>
    </div>
  </div>
  <div class="navigation-profile">
    <%= link_to profile_path, class: "item-navigation", target: "_self",
      title: t("update_profile") do %>
      <div class="row">
        <div class="col-auto">
          <i class="fas fa-user"></i>
        </div>
        <div class="col"><%= t "update_profile" %></div>
        <div class="col-auto">
          <i class="nav-icon-arrow-thin right"></i>
        </div>
      </div>
    <% end %>
    <%= render partial: "shared/nav_item", collection: current_user.restaurants,
      as: "restaurant" %>
  </div>
</div>

app/views/shared/_res_navigation.html.erb
<div class="left">
  <div class="now-navigation-profile">
    <div class="header-profile">
      <div class="row align-items-center">
        <div class="col txt-bold font15"><%= t "restaurant_list" %></div>
      </div>
    </div>
    <div class="navigation-profile">
      <%= render partial: "shared/nav_item",
        collection: current_user.restaurants, as: "restaurant" %>
    </div>
  </div>
  <div class="create-restaurant">
    <%= link_to new_restaurant_path, remote: true do %>
      <button class="btn btn-primary new-res-btn">
        <i class="fas fa-plus"></i>
        <%= t "new_restaurant" %>
      </button>
    <% end %>
  </div>
</div>
<div class="modal" id="new-res-modal">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content modal-create-restaurant">
      <div class="modal-header">
        <span class ="close" data-dismiss="modal">
          <%= image_tag "delete.svg", alt:"delete" %>
        </span>
        <%= t "new_restaurant" %>
      </div>
      <%= form_tag "", method: :post, class: "form-horizontal",
        multipart: true do %>
        <div class="modal-body">
          <div class="form-group restaurant-row">
            <div class="col-2 col-form-label">
              <%= label_tag "restaurant_name", t("restaurant_name") %>
            </div>
            <div class="col-8">
              <%= text_field_tag "new_restaurant[name]", nil, class: "form-control", required: true %>
            </div>
          </div>
          <div class="form-group restaurant-row">
            <div class="col-2 col-form-label">
              <%= label_tag "restaurant_address", t("restaurant_address") %>
            </div>
            <div class="col-8">
              <%= text_field_tag "new_restaurant[address]", nil, class: "form-control", required: true %>
            </div>
          </div>
          <div class="form-group restaurant-row">
            <div class="col-2 col-form-label">
              <%= label_tag "restaurant_phone", t("phone_number") %>
            </div>
            <div class="col-8">
              <%= text_field_tag "new_restaurant[phone_number]", nil,
                class: "form-control", required: true %>
            </div>
          </div>
          <div class="form-group restaurant-row">
            <div class="col-2 col-form-label">
              <%= label_tag "open_time", t("open_time") %>
            </div>
            <div class="col-8">
              <%= text_field_tag "new_restaurant[open_time]", nil,
                class: "form-control", required: true %>
            </div>
          </div>
          <div class="form-group restaurant-row">
            <div class="col-2 col-form-label">
              <%= label_tag "restaurant_image", t("image_dish") %>
            </div>
            <div class="col-8">
              <%= image_tag "", id:"load_create_res_image" %>
            </div>
            <div class="col-2">
              <div class="dish-file-image">
                <%= file_field :new_restaurant, :image, hidden: "true",
                  accept: Settings.valid_image_types.join(",") %>
                <%= label :new_restaurant, :image, class: "label-dish" do %>
                  <%= t "pick" %>
                <% end %>
                <span class="font-italic font13">
                  <%= t "accept_image" %>
                </span>
              </div>
            </div>
          </div>
        </div>
        <div class="modal-footer">
           <button type="button" class="btn close-modal-btn"
            data-dismiss="modal">
            <%= t "close" %>
          </button>
          <button type="submit" class="btn create-res-btn"
            id="create-restaurant">
            <%= t "create_restaurant" %>
          </button>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_search_form.html.erb
<%= search_form_for @q do |f| %>
  <div class="form-search">
    <div class="input-group">
      <%= f.search_field :name_or_address_cont,
        {class: "form__control has-icon list-restaurant__search",
        placeholder: t("search_res")} %>
      <%= f.button type: "submit", class: "btn btn-search" do %>
        <span class="fas fa-search icon icon-search"></span>
      <% end %>
    </div>
  </div>
<% end %>

app/views/shared/_search_item_form.html.erb
<%= search_form_for @q, url: restaurant_path(@restaurant) do |f| %>
  <div class="search-items">
    <p class="input-group">
      <%= f.search_field :name_cont,
        {class: "form__control has-icon list-restaurant__search",
          placeholder: t("search")} %>
      <i class="fas fa-search" type: "submit"></i>
    </p>
  </div>
<% end %>

app/views/shared/_search_order_of_restaurant.html.erb
<%= search_form_for @order, url: orders_restaurant_path	 do |f| %>
  <div class="filter-table">
    <div class="filter-table-item ">
      <div class="text-nowrap">
        <span class="filter-table-label"><%= t "status" %></span>
        <%= f.select(:status_cont , options_for_select(order_status, selected: select_option_status_order), class: "form-control", include_blank: t("all")) %> 
        <%= f.button type: "submit", class: "btn btn-sm" do %>
          <%= t "search" %>
        <% end %>
      </div>
    </div>
  </div>
<% end %>

app/views/shared/_search_order_of_user.html.erb
<%= search_form_for @order do |f| %>
  <div class="filter-table">
    <div class="filter-table-item ">
      <div class="text-nowrap">
        <span class="filter-table-label"><%= t "status" %></span>
        <%= f.select(:status_cont , options_for_select(order_status, selected: select_option_status_order), class: "form-control", include_blank: t("all")) %>
        <%= f.button type: "submit", class: "btn btn-sm" do %>
          <%= t "search" %>
        <% end %>
      </div>
    </div>
  </div>
<% end %>

app/views/shared/_user_navigation.html.erb
<div class="now-navigation-profile user-nav">
  <div class="header-profile">
    <div class="row align-items-center">
      <div class="col-auto">
        <%= image_tag current_user.image, class: "avatar-circle",
          alt: current_user.name %>
      </div>
      <div class="col txt-bold font15"><%= current_user.name %></div>
    </div>
  </div>
  <div class="navigation-profile">
    <%= link_to profile_path, class: "item-navigation active", target: "_self",
      title: t("update_profile") do %>
      <div class="row">
        <div class="col-auto">
          <i class="fas fa-user"></i>
        </div>
        <div class="col"><%= t "update_profile" %></div>
        <div class="col-auto">
          <i class="nav-icon-arrow-thin right"></i>
        </div>
      </div>
    <% end %>
  </div>
</div>