config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|vi/ do
    root "static_pages#home"

    get "/about", to: "static_pages#about"
    get "/contact", to: "static_pages#contact"
    get "/term", to: "static_pages#term"
    get "/security", to: "static_pages#security"
    get "/order_details", to: "order_details#index"

    as :user do
      get "signup", to: "users/registrations#new"
      get "signin", to: "devise/sessions#new"
      post "signin", to: "devise/sessions#create"
      delete "signout", to: "devise/sessions#destroy"
      get "profile", to: "devise/registrations#edit"
      put "profile", to: "devise/registrations#update"
    end

    devise_for :users, controllers: {registrations: "users/registrations"}

    resources :users, only: [:show, :edit, :update]
    resources :restaurants do
      member do
        get :orders
      end
    end
    resources :orders, except: %i(edit destroy)
    resources :dishes
    resources :combos
  end
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  RESTAURANT_PARAMS = %i(name address phone_number open_time image).freeze

  belongs_to :user

  has_many :dishes, dependent: :destroy
  has_many :order_details, through: :dishes
  has_many :orders, dependent: :destroy
  has_many :combos, dependent: :destroy

  has_one_attached :image

  validates :name, presence: true
  validates :address, presence: true
  validates :phone_number, presence: true
  validates :open_time, presence: true
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :load_restaurant, only: %i(show edit update orders)

  def index
    @q = Restaurant.ransack(params[:q])
    @restaurants = @q.result(distinct: true)
                     .page(params[:page]).per Settings.res_per_page
  end

  def show
    @q = @restaurant.dishes.ransack(params[:q])
    @dishes = @q.result(distinct: true)
                .page(params[:page]).per Settings.res_per_page
  end

  def edit; end

  def update
    if @restaurant.update restaurant_params
      attach_image
      flash[:success] = t "restaurant_updated"
    else
      flash[:danger] = t "restaurant_update_fail"
    end
    redirect_to edit_restaurant_url
  end

  def new
    @new_restaurant = current_user.restaurants.build
    respond_to :js
  end

  def create
    @new_restaurant = current_user.restaurants.build new_restaurant_params
    attach_image
    save_restaurant
  end

  def orders
    @order = @restaurant.orders.search(params[:q])
    @orders = @order.result(distinct: true)
                    .page(params[:page]).per Settings.order_page
  end

  private

  def load_restaurant
    @restaurant = Restaurant.find_by id: params[:id]
    return if @restaurant

    flash[:danger] = t "invalid_restaurant"
    redirect_to root_url
  end

  def restaurant_params
    params.require(:restaurant).permit Restaurant::RESTAURANT_PARAMS
  end

  def new_restaurant_params
    params.require(:new_restaurant).permit Restaurant::RESTAURANT_PARAMS
  end

  def save_restaurant
    if @new_restaurant.save
      flash[:success] = t "restaurant_created"
      redirect_to edit_restaurant_url @new_restaurant
    else
      flash[:danger] = t "restaurant_create_fail"
      redirect_to root_url
    end
  end

  def attach_new_image
    return unless params.dig(:new_restaurant, :image)

    @new_restaurant.image.attach params[:new_restaurant][:image]
  end

  def attach_image
    return unless params.dig(:restaurant, :image)

    @restaurant.image.attach params[:restaurant][:image]
  end
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
  def show_sub_navigation restaurant
    "show" if correct_restaurant?(restaurant)
  end

  def active_navigation restaurant
    "active" if correct_restaurant?(restaurant)
  end

  def active_update_restaurant restaurant
    "active" if correct_restaurant?(restaurant) && params[:action] == "edit"
  end

  def active_orders_list restaurant
    "active" if correct_restaurant?(restaurant) && params[:action] == "orders"
  end
end

app/views/restaurants/_box_loading.html.erb
<div class="box-loading">
  <div class="box-thumbnail"></div>
  <div class="box-line-df"></div>
  <div class="box-line-lgx"></div>
  <div class="box-line-lg"></div>
</div>

app/views/restaurants/_item.html.erb
<li>
  <div class="item-restaurant-row">
    <div class="row">
      <div class="col-auto item-restaurant-img">
        <button class="inline">
          <%= image_tag dish.image %>
        </button>
      </div>
      <div class="col item-restaurant-info">
        <div class="item-restaurant-name"><%= dish.name %></div>
        <div class="item-restaurant-desc"><%= dish.description %></div>
        <div class="item-restaurant-total">
          <%= t "ordered" %>
          <span class="txt-bold"><%= t "num_orders" %></span>
          <%= t "times" %>
        </div>
      </div>
      <div class="col-auto item-restaurant-more">
        <div class="row ">
          <div class="col-auto product-price">
            <div class="old-price">
              <%= dish.price %>
              <span class= "food_price">
                <%= t "dong" %>
              </span>
            </div>
            <div class="current-price">
              <%= dish.price*(100-@restaurant.discount)/100 %>
              <span class= "food_price">
                <%= t "dong" %>
              </span>
            </div>
          </div>
          <div class="col-auto adding-food-cart txt-right">
            <div class="btn-adding" data-id="<%= dish.id %>">+</div>
          </div>
        </div>
      </div>
    </div>
  </div>
</li>

app/views/restaurants/_restaurant.html.erb
<div class="item-restaurant">
  <%= link_to restaurant, class: "item-content", target: "_self" do %>
    <div class="img-restaurant">
      <%= image_tag restaurant.image, class: "" %>
    </div>
    <div class="info-restaurant">
      <div class="info-basic-res">
        <h4 class="name-res" title="<%= restaurant.name %>">
          <%= restaurant.name %>
        </h4>
        <div class="address-res" title="<%= restaurant.address %>">
          <%= restaurant.address %>
        </div>
      </div>
      <p class="content-promotion">
        <i class="fas fa-tag"></i>
        <%= t "sale_all", percent: restaurant.discount %>
      </p>
      <div class="opentime-status">
        <span class="stt online" title="<%= t "open" %>"></span>
      </div>
    </div>
  <% end %>
</div>

app/views/restaurants/edit.html.erb
<div class="container">
  <%= render "shared/res_navigation" %>
  <div class="now-detail-profile">
    <div class="header-user-profile"><%= t "restaurant_info" %></div>
    <div class="content-user-profile">
      <%= form_for @restaurant do |f| %>
        <div class="user-profile-update">
          <div class="title-user"><%= t "upload_res_avatar" %></div>
          <div class="row upload-res-avt">
            <div class="col-8">
              <div class="restaurant-avatar-image">
                <%= image_tag @restaurant.image, alt: @restaurant.name,
                  id: "load_res_image" %>
              </div>
            </div>
            <div class="col-4">
              <div class="form-group">
                <div class="restaurant-file-image">
                  <span><%= t "upload_from" %></span>
                  <%= f.file_field :image, hidden: "true",
                    accept: Settings.valid_image_types.join(",") %>
                  <%= f.label :image, class: "label-custom" do %>
                    <%= t "pick" %>
                  <% end %>
                </div>
                <span class="font-italic font13">
                  <%= t "accept_image" %>
                </span>
              </div>
            </div>
          </div>
        </div>
        <div class="user-profile-update">
          <div class="title-user"><%= t "change_info" %></div>
          <div class="row form-group align-items-center">
            <div class="col-2 txt-bold"><%= t "restaurant_name" %></div>
            <div class="col-4">
              <div class="input-group">
                <%= f.text_field :name, class: "form-control",
                  placeholder: t("restaurant_name") %>
              </div>
            </div>
          </div>
          <div class="row form-group align-items-center">
            <div class="col-2 txt-bold"><%= t "phone_number" %></div>
            <div class="col-4">
              <div class="input-group">
                <%= f.text_field :phone_number, class: "form-control",
                  placeholder: t("phone_number") %>
              </div>
            </div>
          </div>
          <div class="row form-group align-items-center">
            <div class="col-2 txt-bold"><%= t "restaurant_address" %></div>
            <div class="col-4">
              <div class="input-group">
                <%= f.text_area :address, class: "form-control",
                  placeholder: t("restaurant_address") %>
              </div>
            </div>
          </div>
          <div class="row">
            <div class="col-3">
              <button type="submit" class="btn btn-blue-4 btn-block">
                <%= t "save_change" %>
              </button>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/restaurants/index.html.erb
<div class="container">
  <%= render "shared/search_form" %>
  <% if @restaurants.present? %>
    <div class="now-list-restaurant deal-tab">
      <div class="list-restaurant clearfix">
        <div class="now-loading-restaurant">
          <%= render "box_loading", collection: @restaurants %>
        </div>
        <%= render @restaurants %>
      </div>
      <center><%= paginate @restaurants %></center>
    </div>
  <% end %>
</div>

app/views/restaurants/new.js.erb
$('#new-res-modal form').attr('action', '<%= restaurants_url(@new_restaurant) %>');
$('#new-res-modal').modal('show');

app/views/restaurants/orders.html.erb
<div class="block-section">
  <div class="container">
    <div class="now-incoming incoming-full">
      <div class="slick-slider slick-initialized">
        <div class="slick-list">
          <div class="slick-track">
          </div>
        </div>
      </div>
    </div>
    <div class="now-incoming incoming-full mt-5">
      <div class="slick-slider slick-initialized">
        <div class="slick-list">
          <div class="slick-track"></div>
        </div>
      </div>
    </div>
    <div class="table-cancel-confirm-container">
    </div>
    <h1 class="block-title mb-4 text-center"><%= t "all_order" %></h1>
    <div class="history-switch">
      <div class="item now active"><%= t "welcome" %></div>
    </div>
    <div class="history-table-container">
      <%= render "shared/search_order_of_restaurant" %>
      <div class="history-table1">
        <div class="history-table1-row history-table-heading">
          <div class="history-table1-cell history-table1-col1"><%= t "number" %></div>
          <div class="history-table1-cell history-table1-col2"><%= t "customer_name" %></div>
          <div class="history-table1-cell history-table1-col3"><%= t "time" %></div>
          <div class="history-table1-cell history-table1-col4"><%= t "place" %></div>
          <div class="history-table1-cell history-table1-col5"><%= t "total_money" %></div>
          <div class="history-table1-cell history-table1-col6"><%= t "status" %></div>
          <div class="history-table1-cell history-table1-col7"><%= t "details" %></div>
          <div class="history-table1-cell history-table1-col8"><%= t "action" %></div>
        </div>
        <% @orders.each_with_index do |order, index| %>
          <div class="history-table1-row ">
            <div class="history-table1-cell history-table1-col1">
              <%= page_index params[:page], index, Settings.order_page %>
            </div>
            <div class="history-table1-cell history-table1-col2">
              <%= order.user_name %>
            </div>
            <div class="history-table1-cell history-table1-col3">
              <%= order.created_at.strftime(Settings.time_format) %>
            </div>
            <div class="history-table1-cell history-table1-col4">
              <%= order.address %>
            </div>
            <div class="history-table1-cell history-table1-col5">
              <%= order.total_money %>
            </div>
            <div class="history-table1-cell history-table1-col6" id="order_status_<%= order.id %>">
              <%= order.status.humanize %>
            </div>
            <div class="history-table1-cell history-table1-col7">
              <%= link_to t("detail"), order_details_path(id: order.id) %>
            </div>
            <div class="history-table1-cell history-table1-col8" id ="render_button_<%= order.id %>">
              <%= render "shared/button", order: order %>
            </div>
          </div>
        <% end %>
      </div>
      <%= paginate @orders %>
    </div>
  </div>
</div>

app/views/restaurants/show.html.erb
<% provide :title, @restaurant.name %>
<div class="now-detail-restaurant clearfix">
  <div class="container">
    <div class="detail-restaurant-img">
      <%= image_tag @restaurant.image, alt: @restaurant.name %>
    </div>
    <div class="detail-restaurant-info">
      <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
          <li class="breadcrumb-item">
            <%= link_to t("home"), root_url, class: "breadcrumb-link",
            rel: "nofollow" %>
          </li>
          <li class="breadcrumb-item">
            <%= link_to @restaurant.name, @restaurant,
            class: "breadcrumb-link", rel: "nofollow" %>
          </li>
        </ol>
      </nav>
      <div class="kind-restaurant"><%= t "restaurant_kind" %></div>
      <div class="name-restaurant"><%= @restaurant.name %></div>
      <div class="address-restaurant"><%= @restaurant.address %></div>
      <div class="rating">
        <div class="stars">
          <span class="full"><i class="fas fa-star"></i></span>
          <span class="full"><i class="fas fa-star"></i></span>
          <span class="full"><i class="fas fa-star"></i></span>
          <span class="full"><i class="fas fa-star"></i></span>
          <span class="half"><i class="fas fa-star-half-alt"></i></span>
        </div>
        <span class="number-rating"><%= t "number_rates" %></span>
        <%= t "rate_from" %>
      </div>
      <div class="status-restaurant">
        <div class="opentime-status">
          <span class="stt offline" title="<%= t "restaurant_status"%>"></span>
        </div>
      </div>
      <div class="share-social clearfix">
        <div class="share-social-box">
          <div class="fb-like" data-layout="button" data-action="like"
          data-size="small" data-show-faces="false" data-share="true"
          data-colorscheme="light" data-kid-directed-site="false"></div>
        </div>
      </div>
      <div class="utility-restaurant clearfix">
        <div class="utility-item">
          <div class="utility-title"><%= t "service_fee" %></div>
          <div class="utility-content">
            <span class="txt-bold txt-red"><%= t "no_fee" %></span>
          </div>
          <span class="icon icon-verify-merchant" data-toggle="modal"
          data-target="#modal-verify-merchant"></span>
        </div>
        <div class="utility-item">
          <div class="utility-title"><%= t "service_by" %></div>
          <div class="utility-content">
            <span class="txt-bold txt-red"><%= t "sun" %></span>
          </div>
        </div>
        <div class="utility-item">
          <div class="utility-title"><%= t "prepare" %></div>
          <div class="utility-content"><%= t "prepare_time" %></div>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="container relative clearfix">
  <div class="now-menu-restaurant">
    <div class="menu-restaurant-tab">
      <div class="item active"><%= t "menu" %></div>
    </div>
    <div class="menu-restaurant-content-tab">
      <div class="menu-restaurant-container">
        <div class="menu-restaurant-detail">
          <div class="promotions-order">
            <div class="promotion-item">
              <%= image_tag "promo-code.png", class: "icon-promotion" %>
              <div class="content">
                <%= t "sale_promotion", percent: @restaurant.discount %>
              </div>
            </div>
            <div class="promotion-item group-order-campaign">
              <%= image_tag "freeship.png", class: "icon-promotion" %>
              <div class="content"><%= t "freeship" %></div>
            </div>
          </div>
          <div class="menu-restaurant-list">
            <%= render "shared/search_item_form" %>
            <div id="restaurant-item">
              <div aria-label="grid" aria-readonly="true" class="food_list"
                role="grid" tabindex="0">
              <div class="food_list_container" role="rowgroup">
              <ul>
                <%= render partial: "item", collection: @dishes,
                as: :dish %>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<div>
  <div class="now-bill-restaurant">
    <div class="bill-restaurant-header">
      <button disabled="" class="cart-stats">
        <span class="txt-bold" id="total-order-number"><%= t "zero" %></span>
        <%= t "item" %>
      </button>
      <button class="btn-reset" id="btn-reset">
        <%= t "reset" %>
      </button>
      <% if user_signed_in? %>
        <div class="create-order">
          <%= t "order_by" %>
          <span class="txt-blue">
            <%= current_user.name %>
          </span>
        </div>
      <% end %>
    </div>
    <div class="now-order-card-group" id="now-order-card-group"></div>
    <div class="row-bill-restaurant">
      <div class="row">
        <div class="col">
          <%= t "sub_total" %>
        </div>
        <div class="col-auto">
          <span class="txt-bold">
            <span class="total-amount"><%= t "zero" %></span>
            <span class="amount">
              <%= t "dong" %>
            </span>
          </span>
        </div>
      </div>
    </div>
    <div class="row-bill-restaurant txt-center input-promocode">
      <%= t "input_discount" %>
    </div>
    <div class="row-bill-restaurant relative">
      <div class="row">
        <div class="col">
          <%= t "total" %>
        </div>
        <div class="col-auto">
          <span class="txt-bold txt-blue font16">
            <span class="total-amount"><%= t "zero" %></span>
            <span class="amount">
              <%= t "dong" %>
            </span>
          </span>
        </div>
      </div>
    </div>
    <button class="btn btn-red" id = "button_order" data-toggle="modal"
      data-target="#modal-order" data-backdrop="static" data-keyboard="false">
      <i class="fas fa-check-circle" data-id="<%= @restaurant.id %>"></i>
        <%= t "order_now" %>
    </button>
  </div>
</div>

<%= form_tag orders_path, id: "submit-form", method: "post" do %>
  <div class="modal" id="modal-order">
    <div class="modal-dialog modal-dialog-centered">
      <div class="modal-content modal-order-detail">

        <div class="modal-header">
          <span class ="close" data-dismiss="modal">
          <%= image_tag "delete.svg", alt:"delete" %>
        </span>
          <%= t "order_confirmation" %>
        </div>
        <div class="modal-body">
          <div class="order-right">
            <p class="title-popup-order">
              <%= t "order_detail" %>
              <i class="icon-arrow-thin right" aria-hidden="true"></i>
            </p>
            <div class="order-list">
            </div>
            <div class="col-auto">
              <span class="txt-bold txt-blue font16">
                <span class="total-amount">
                </span>
                <span class="amount"></span>
              </span>
            </div>
            <div class="info-order">
              <div class="row">
                <div class="col"><%= t "total" %>
                  <span class="txt-bold" id = "number_set">
                  </span> <%= t "set" %>
                </div>
                <div class="col-auto txt-bold" >
                  <span id ="total_amount"></span>
                  <span class="money_unit">
                    <%= t "dong" %>
                  </span>
                </div>
              </div>
              <div class="row">
                <div class="col-auto">
                  <span class="money_unit">
                  </span>
                </div>
              </div>
            </div>
            <div class="note-order "></div>
            <div class="padding-10 txt-bold font16">
              <div class="row">
                <div class="col-auto">
                  <span class="money_unit">
                  </span>
                </div>
              </div>
            </div>
            <div class="payment-methods">
              <div class="row">
                <div class="col">
                  <span class="txt-bold font16 txt-black"><%= t "cash" %></span>
                </div>
                <div class="col-auto">
                  <i class="icon-arrow-thin right" aria-hidden="true"></i>
                </div>
              </div>
            </div>
            <div class="order-note">
              <label for="address"><%= t "address" %></label>
              <textarea placeholder="<%= t "example_place" %>" id="input-address" required></textarea>
            </div>
            <div class="not-vat">
              <span class="icon icon-vatnot">
                <%= image_tag "VAT.jpg", alt:"vat" %>
              </span>
              <span class="txt-gray"><%= t "not_export_vat" %></span>
            </div>
          </div>
        </div>
        <div class="modal-footer">
            <button class="submit-order" id="btn-submit-form">
              <%= t "order" %>
              <i class="fas fa-arrow-right"></i>
              <span class="total-price">
                <div>
                  <span class="money_unit">
                  </span>
                </div>
              </span>
            </button>
        </div>
      </div>
    </div>
  </div>
<% end %>