config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|vi/ do
    root "static_pages#home"

    get "/about", to: "static_pages#about"
    get "/contact", to: "static_pages#contact"
    get "/term", to: "static_pages#term"
    get "/security", to: "static_pages#security"
    get "/order_details", to: "order_details#index"

    as :user do
      get "signup", to: "users/registrations#new"
      get "signin", to: "devise/sessions#new"
      post "signin", to: "devise/sessions#create"
      delete "signout", to: "devise/sessions#destroy"
      get "profile", to: "devise/registrations#edit"
      put "profile", to: "devise/registrations#update"
    end

    devise_for :users, controllers: {registrations: "users/registrations"}

    resources :users, only: [:show, :edit, :update]
    resources :restaurants do
      member do
        get :orders
      end
    end
    resources :orders, except: %i(edit destroy)
    resources :dishes
    resources :combos
  end
end

app/models/combo.rb
class Combo < ApplicationRecord
  COMBO_PARAMS = [:name, :description, :image, :price,
                    combo_details_attributes: [:dish_id, :count]].freeze

  belongs_to :restaurant

  has_many :combo_details, dependent: :destroy
  has_many :dishes, through: :combo_details, dependent: :destroy
  has_many :order_details, as: :order_detailable, dependent: :destroy
  has_many :orders, through: :order_details, dependent: :destroy
  has_one_attached :image

  validates :name, :description, presence: true

  accepts_nested_attributes_for :combo_details, allow_destroy: true
end

app/controllers/combos_controller.rb
class CombosController < ApplicationController
  before_action :load_restaurant, only: %i(new create index update)
  before_action :load_combo, only: %i(edit update)

  def index
    @combos = @restaurant.combos.page(params[:page]).per Settings.combo_per_page
    @dishes = @restaurant.dishes.page(params[:page])
  end

  def new
    @combo = @restaurant.combos.build
    respond_to :js
  end

  def create
    @combo = @restaurant.combos.build combo_params
    attach_image
    save_combo
  end

  def edit
    respond_to :js
  end

  def update
    @combo.combo_details.destroy_all
    if @combo.update combo_params
      attach_image
      flash[:success] = t "combo_updated"
    else
      flash[:danger] = t "combo_update_fail"
    end
    redirect_to combos_url(res_id: @restaurant.id)
  end

  private

  def combo_params
    params.require(:combo).permit Combo::COMBO_PARAMS
  end

  def load_combo
    @combo = Combo.find_by id: params[:id]
    return if @combo

    flash[:danger] = t "not_exist"
    redirect_to root_url
  end

  def save_combo
    if @combo.save
      flash[:success] = t "combo_created"
      redirect_to combos_url(res_id: @restaurant.id)
    else
      flash[:danger] = t "combo_create_fail"
      redirect_to root_url
    end
  end

  def attach_image
    return unless params.dig(:combo, :image)

    @combo.image.attach params[:combo][:image]
  end

  def load_restaurant
    @restaurant = Restaurant.find_by id: params[:res_id]
    return if @restaurant

    flash[:danger] = t "not_exist"
    redirect_to root_url
  end
end

app/helpers/combos_helper.rb
module CombosHelper
  def active_combos_list restaurant
    "active" if correct_restaurant?(restaurant) && combos_controller?
  end

  def combos_controller?
    params[:controller] == "combos" && params[:action] == "index"
  end
end

app/views/combos/_combo_modal.html.erb
<div class="modal" id="combo-modal">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content modal-create-combo">
      <div class="modal-header">
        <span class ="close" data-dismiss="modal">
          <%= image_tag "delete.svg", alt:"delete" %>
        </span>
        <div id="modal-combo-title">
        </div>
      </div>
      <%= form_tag "", id: "combo-form", method: :post, class: "form-horizontal",
        multipart: true do %>
        <input type="hidden" name="_method">
        <input type="hidden" name="res_id" value="<%= @restaurant.id %>">
        <div class="modal-body">
          <div class="combo-info">
            <div class="form-group dish-row">
              <div class="col-4 col-form-label">
                <%= label_tag "combo_name", t("combo_name") %>
              </div>
              <div class="col-8">
                <%= text_field_tag "combo[name]", nil, class: "form-control",
                  required: true %>
              </div>
            </div>
            <div class="form-group dish-row">
              <div class="col-4 col-form-label">
                <%= label_tag "combo_price", t("price") %>
              </div>
              <div class="col-8">
                <%= number_field_tag "combo[price]", nil, class: "form-control",
                  min: Settings.min_price, step: Settings.price_step,
                  required: true %>
              </div>
            </div>
            <div class="form-group dish-row">
              <div class="col-4 col-form-label">
                <%= label_tag "combo_description", t("description") %>
              </div>
              <div class="col-8">
                <%= text_field_tag "combo[description]", nil,
                  class: "form-control", required: true %>
              </div>
            </div>
            <div class="form-group dish-row">
              <div class="col-4 col-form-label">
                <%= label_tag "combo_image", t("image") %>
              </div>
              <div class="col-4">
                <%= image_tag "", id:"load_combo_image" %>
              </div>
              <div class="col-4">
                <div class="dish-file-image">
                  <%= file_field :combo, :image, hidden: "true",
                    accept: Settings.valid_image_types.join(",") %>
                  <%= label :combo, :image, class: "label-dish" do %>
                    <%= t "pick" %>
                  <% end %>
                  <span class="font-italic font13">
                    <%= t "accept_image" %>
                  </span>
                </div>
              </div>
            </div>
          </div>
          <div class="combo-detail">
            <div class="combo-detail-title">
              <%= t "combo_detail" %>
              <div class="add-dish-to-cb">
                  <button type="button" class="add-dish-to-cb-btn",
                    data-toggle="modal" data-target="#dishes-list-modal">
                    <i class="fas fa-plus"></i>
                  </button>
                </div>
            </div>
            <div class="dishes-group", id="dishes-group">
              <div class="dishes-table-row dishes-table-heading">
                <div class="dishes-table-cell dishes-table-col1">
                  <%= t "dish_name" %>
                </div>
                <div class="dishes-table-cell dishes-table-col2">
                  <%= t "image" %>
                </div>
                <div class="dishes-table-cell dishes-table-col3">
                  <%= t "price" %>
                </div>
                <div class="dishes-table-cell dishes-table-col4">
                  <%= t "count" %>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="modal-footer">
           <button type="button" class="btn close-modal-btn"
            data-dismiss="modal">
            <%= t "close" %>
          </button>
          <button type="submit", id="modal-submit-btn">
          </button>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/combos/_dishes_list_modal.html.erb
<div class="modal" id="dishes-list-modal">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content modal-dishes-list">
      <div class="modal-header">
        <span class ="close" data-dismiss="modal">
          <%= image_tag "delete.svg", alt:"delete" %>
        </span>
        <div id="modal-dishes-title">
          <%= t "dish_list" %>
        </div>
      </div>
      <div class="modal-body">
        <div class="dishes-list">
          <div class="dishes-group", id="dishes-list">
            <div class="dishes-table-row dishes-table-heading">
              <div class="dishes-table-cell dishes-table-col1">
                <%= t "dish_name" %>
              </div>
              <div class="dishes-table-cell dishes-table-col2">
                <%= t "image" %>
              </div>
              <div class="dishes-table-cell dishes-table-col3">
                <%= t "price" %>
              </div>
            </div>
            <% @dishes.each_with_index do |dish, n| %>
              <div class="dishes-table-row dishes-table-item"
                data-id="<%= dish.id %>">
                <div class="dishes-table-cell dishes-table-col1">
                  <%= dish.name %>
                </div>
                <div class="dishes-table-cell dishes-table-col2">
                  <%= image_tag dish.image %>
                </div>
                <div class="dishes-table-cell dishes-table-col3">
                  <%= dish.price %> đ
                </div>
              </div>
            <% end %>
          </div>
        </div>
      </div>
      <div class="modal-footer">
         <button type="button" class="btn close-modal-btn"
          data-dismiss="modal">
          <%= t "close" %>
        </button>
      </div>
    </div>
  </div>
</div>

app/views/combos/edit.js.erb
$('#combo-modal form').attr('action', '<%= combo_url(@combo) %>');
$('input[name="_method"]').val('patch');
$('#combo_name').val('<%= @combo.name %>');
$('#combo_price').val('<%= @combo.price %>');
$('#combo_description').val('<%= @combo.description %>');
$('#load_combo_image').attr('src', '<%= url_for(@combo.image) %>');
$('#modal-combo-title').html('<%= t "update_combo" %>');
$('#modal-submit-btn').html('<%= t "update" %>');
$('#modal-submit-btn').removeClass();
$('#modal-submit-btn').addClass('update-combo-btn btn');
var comboDishes = $('#dishes-group').find('.dishes-table-item');
var dishes = $('#dishes-list').find('.dishes-table-item');

for (let i = 0;i < comboDishes.length;i++) {
  delDishFromCb($(comboDishes[i]).find('.del-dish-from-cb')[0]);
}

for (let i = 0;i < dishes.length; i++) {
  $(dishes[i]).off();
  $(dishes[i]).on('click', function() {addDishToCombo(this);});
}

var dishes = $('#dishes-list').find('.dishes-table-item');
<% @combo.dishes.each_with_index do |dish, i| %>
  var dishId = '<%= dish.id %>';
  var dishName = '<%= dish.name %>';
  var dishPrice = '<%= dish.price %>';
  var dishImageSrc = '<%= url_for(dish.image) %>';
  var count = '<%= @combo.combo_details[i].count %>';
  var dishRow = `<div class='dishes-table-row dishes-table-item' data-id='\
    ${dishId}\
    '>
    <div class='dishes-table-cell dishes-table-col1'>\
    ${dishName}\
    </div>
    <div class='dishes-table-cell dishes-table-col2'>
    <img src='\
    ${dishImageSrc}\
    '>
    </div>
    <div class='dishes-table-cell dishes-table-col3'>\
    ${dishPrice}\
    </div>
    <div class='dishes-table-cell dishes-table-col4'>
    <input type='number', min='0', step='1', value=\
    ${count}\
    , required='true'/>
    </div>
    <div class='dishes-table-cell dishes-table-col5'>
    <button type = "button" class="del-dish-from-cb">
    <i class="fas fa-times"></i>
    </button>
    </div>
    </div>`;
  $('#dishes-group').append(dishRow);
  for (let i = 0;i < dishes.length;i++) {
    if (dishes[i].dataset.id == <%= dish.id %>) {
      $(dishes[i]).remove();
      break;
    }
  }
<% end %>

var deleteBtns = $('.del-dish-from-cb');

for (let i = 0;i < deleteBtns.length; i++) {
  $(deleteBtns[i]).on('click', function() {delDishFromCb(this);});
}

$('#combo-modal').modal('show');

var old_btn = $('.update-combo-btn')[0]
var new_btn = old_btn.cloneNode(true);
old_btn.parentNode.replaceChild(new_btn, old_btn);

$($('.update-combo-btn')[0]).on('click', function(e) {
  e.preventDefault();
  updateCombo();
});

function updateCombo() {
  var formData = new FormData($('form#combo-form')[0]);
  var comboDishes = $('#dishes-group').find('.dishes-table-item');
  var dishesLength = comboDishes.length;

  for (let i = 0; i < dishesLength; i++){
    let dishId = comboDishes[i].dataset.id;
    let count = $($(comboDishes[i]).find('.dishes-table-col4')[0]).find(':input')[0].value;
    formData.append('combo[combo_details_attributes][' + i + '][dish_id]', dishId);
    formData.append('combo[combo_details_attributes][' + i + '][count]', count);
  }

  $.ajax({
    type: "POST",
    url: "/combos/" + "<%= @combo.id %>",
    data: formData,
    processData: false,
    contentType: false,
  });
}

app/views/combos/index.html.erb
<div class="container">
  <%= render "shared/res_navigation" %>
  <div class="now-detail-profile">
    <div class="header-user-profile">
      <%= t "combos_list" %>
      <div class="create-combo">
        <%= link_to new_combo_path(res_id: @restaurant.id), remote: true do %>
          <button class="btn btn-primary new-res-btn">
            <i class="fas fa-plus"></i>
            <%= t "new_combo" %>
          </button>
        <% end %>
      </div>
    </div>
    <div class="dishes-list">
      <div class="dishes-table">
        <div class="dishes-table-row dishes-table-heading">
          <div class="dishes-table-cell dishes-table-col1"><%= t "num" %></div>
          <div class="dishes-table-cell dishes-table-col2">
            <%= t "combo_name" %>
          </div>
          <div class="dishes-table-cell dishes-table-col3">
            <%= t "image" %>
          </div>
          <div class="dishes-table-cell dishes-table-col4">
            <%= t "price" %>
          </div>
          <div class="dishes-table-cell dishes-table-col5">
            <%= t "description" %>
          </div>
          <div class="dishes-table-cell dishes-table-col6">
            <%= t "is_ordered" %>
          </div>
          <div class="dishes-table-cell dishes-table-col7">
            <%= t "action" %>
          </div>
        </div>
        <% @combos.each_with_index do |combo, n| %>
          <div class="dishes-table-row dishes-table-item">
            <div class="dishes-table-cell dishes-table-col1"><%= n+1 %></div>
            <div class="dishes-table-cell dishes-table-col2">
              <%= combo.name %>
            </div>
            <div class="dishes-table-cell dishes-table-col3">
              <%= image_tag combo.image %>
            </div>
            <div class="dishes-table-cell dishes-table-col4">
              <%= combo.price %> đ
            </div>
            <div class="dishes-table-cell dishes-table-col5">
              <%= combo.description %>
            </div>
            <div class="dishes-table-cell dishes-table-col6">
              <%= combo.orders.size %>
            </div>
            <div class="dishes-table-cell dishes-table-col7">
              <%= link_to t("edit"), edit_combo_path(combo), remote: true %>
              &nbsp;
              <%= link_to t("delete"), "", class: "delete-dish" %>
            </div>
          </div>
        <% end %>
        <%= paginate @combos %>
      </div>
    </div>
  </div>
</div>
<%= render "combo_modal" %>
<%= render "dishes_list_modal" %>

app/views/combos/new.js.erb
$('#combo-modal form').attr('action', '<%= combos_url(@combo) %>');
$('input[name="_method"]').val('post');
$('#modal-combo-title').html('<%= t "create_combo" %>');
$('#modal-submit-btn').html('<%= t "create" %>');
$('#modal-submit-btn').removeClass();
$('#modal-submit-btn').addClass('create-combo-btn btn');
$('#combo_name').val('');
$('#combo_price').val('');
$('#combo_description').val('');
$('#load_combo_image').attr('src', '');
$('#combo-modal').modal('show');

var comboDishes = $('#dishes-group').find('.dishes-table-item');
var dishes = $('#dishes-list').find('.dishes-table-item');

for (let i = 0;i < comboDishes.length;i++) {
  delDishFromCb($(comboDishes[i]).find('.del-dish-from-cb')[0]);
}

for (let i = 0;i < dishes.length; i++) {
  $(dishes[i]).off();
  $(dishes[i]).on('click', function() {addDishToCombo(this);});
}

$($('.create-combo-btn')[0]).off();

$('.create-combo-btn')[0].addEventListener('click', function(e) {
  e.preventDefault();
  createCombo();
});

function createCombo() {
  var formData = new FormData($('form#combo-form')[0]);
  var comboDishes = $('#dishes-group').find('.dishes-table-item');
  var dishesLength = comboDishes.length;

  for(let i = 0; i < dishesLength; i++){
    let dishId = comboDishes[i].dataset.id;
    let count = $($(comboDishes[i]).find('.dishes-table-col4')[0]).find(':input')[0].value;
    formData.append('combo[combo_details_attributes][' + i + '][dish_id]', dishId);
    formData.append('combo[combo_details_attributes][' + i + '][count]', count);
  }

  $.ajax({
    type: "POST",
    url: "/combos",
    data: formData,
    processData: false,
    contentType: false,
  });
}