config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|vi/ do
    root "static_pages#home"

    get "/about", to: "static_pages#about"
    get "/contact", to: "static_pages#contact"
    get "/term", to: "static_pages#term"
    get "/security", to: "static_pages#security"
    get "/order_details", to: "order_details#index"

    as :user do
      get "signup", to: "users/registrations#new"
      get "signin", to: "devise/sessions#new"
      post "signin", to: "devise/sessions#create"
      delete "signout", to: "devise/sessions#destroy"
      get "profile", to: "devise/registrations#edit"
      put "profile", to: "devise/registrations#update"
    end

    devise_for :users, controllers: {registrations: "users/registrations"}

    resources :users, only: [:show, :edit, :update]
    resources :restaurants do
      member do
        get :orders
      end
    end
    resources :orders, except: %i(edit destroy)
    resources :dishes
    resources :combos
  end
end

app/views/layouts/_footer.html.erb
<footer class="main-footer">
  <div class="container">
    <div class="container-inner">
      <div class="block-footer">
        <p class="title-block"><%= t "company" %></p>
        <ul class="menu-footer">
          <li class="menu-item">
            <%= link_to t("about"), about_path %>
          </li>
          <li class="menu-item">
            <%= link_to t("term"), term_path %>
          </li>
          <li class="menu-item">
            <%= link_to t("term_of_user"), "#" %>
          </li>
          <li class="menu-item">
            <%= link_to t("security"), security_path %>
          </li>
          <li class="menu-item">
            <%= link_to t("contact"), contact_path %>
          </li>
        </ul>
      </div>
      <div class="block-footer">
        <p class="title-block"><%= t "sun_app" %></p>
        <%= link_to "#", target: "_blank", rel: "noopener noreferrer nofollow",
          title: t("down_ios") do %>
          <span class="apps app-ios" title=<%= t("down_ios") %>>
            <i class="fab fa-apple"></i>
            iOS
          </span>
        <% end %>
        <%= link_to "#", target: "_blank", rel: "noopener noreferrer nofollow",
          title: t("down_android") do %>
          <span class="apps app-android" title=<%= t("down_android") %>>
            <i class="fab fa-android"></i>
            Android
          </span>
        <% end %>
      </div>
      <div class="block-footer txt-center">
        <div class="logo-footer">
          <%= link_to image_tag("logo_1.png", alt:"logo_now",
          class: "cover"), "#" %>
        </div>
        <p class="font12"><%= t "copy_right" %></p>
        <ul class="social-ico">
          <li>
            <%= link_to Settings.facebook, target: "_blank",
              rel: "noopener noreferrer nofollow", title: "Facebook" do %>
              <span class="facebook ico">
                <i class="fab fa-facebook-f"></i>
              </span>
            <% end %>
          </li>
          <li>
            <span class="google ico">
              <i class="fab fa-google-plus-g"></i>
            </span>
          </li>
          <li>
            <%= link_to Settings.instagram, target: "_blank",
              rel: "noopener noreferrer nofollow", title: "Instagram" do %>
              <span class="instagram ico">
                <i class="fab fa-instagram">
                </i>
              </span>
            <% end %>
          </li>
        </ul>
      </div>
      <div class="block-last">
        <p class="title-block"><%= t "company_address" %></p>
        <span>
          <p><%= t "company_name" %></p>
          <p><%= t "com_addr_first_line" %></p>
          <p><%= t "com_addr_second_line" %></p>
          <p><%= t "certificate_first_line" %></p>
          <p><%= t "certificate_second_line" %></p>
          <p><%= t "certificate_third_line" %></p>
          <p><%= t "telephone" %></p>
          <p><%= t "our_email" %></p>
        </span>
        <span class="registered">
          <%= link_to image_tag("gov.png", alt: t("registered"),
            title: t("registered"),
            rel: "noopener noreferrer nofollow", target: "_blank") ,
            Settings.gov%>
        </span>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header class="main-header">
  <div class="container-header">
    <div class="container">
      <div class="header-content navbar row justify-content-between
        align-items-center">
        <div class="logo-now col-auto">
          <span>
            <%= link_to image_tag("logo.png", alt:"rails_logo",
              class: "cover"), root_url, target: "_self" %>
          </span>
        </div>
        <div class="main-nav col">
          <%= link_to t("restaurant"), root_url, class:"nav-item active" %>
        </div>
        <div class="user-acc col-auto">
          <% if user_signed_in? %>
            <div class="dropdown">
              <div class="dropdown-toggle" role="button" id="user-dropdown"
                data-toggle="dropdown">
                <div class="img">
                  <%= image_tag current_user.image %>
                </div>
                <span class="name">
                  <%= current_user.name %>
                </span>
              </div>
              <div class="dropdown-menu" id="drop-menu"
                aria-labelledby="user-dropdown">
                <%= link_to orders_path, target: "_self" do %>
                  <div class="dropdown-item">
                    <span class="text">
                      <%= t "order_history" %>
                    </span>
                  </div>
                <% end %>
                <%= link_to profile_path, target: "_self" do %>
                  <div class="dropdown-item">
                    <span class="text">
                      <%= t "update_account" %>
                    </span>
                  </div>
                <% end %>
                <% if current_user.boss? %>
                  <%= link_to edit_restaurant_path(current_user.restaurants.first), target: "_self" do %>
                    <div class="dropdown-item">
                      <span class="text">
                        <%= t "manage_restaurants" %>
                      </span>
                    </div>
                  <% end %>
                <% end %>
                <%= link_to signout_path, target: "_self", method: :delete do %>
                  <div class="dropdown-item">
                    <span class="text">
                      <%= t "log_out" %>
                    </span>
                  </div>
                <% end %>
              </div>
            </div>
          <% else %>
            <%= link_to signin_path do %>
              <button type="button" class="btn btn-none-bg btn-login">
                <%= t "log_in" %>
              </button>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title yield(:title) %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", media: "all",
      "data-turbolinks-track": "reload" %>
    <%= javascript_pack_tag "application", "data-turbolinks-track": "reload" %>
  </head>

  <body>
    <div class="app">
      <div class="wrapper">
        <%= render "layouts/header" %>
        <div class="container">
          <% flash.each do |message_type, message| %>
            <div class="alert alert-<%= message_type %>"><%= message %></div>
          <% end %>
        </div>
        <%= yield %>
      </div>
      <%= render "layouts/footer" %>
      </div>
    </div>
  </body>
</html>